Sql:
  Host: ""
  Database: ""
  Username: ""
  Password: ""
Refresh: 600000
Tracks:
  Shmezi:
    Cool:
      Price: 10
      Time: 10 # Amount of time in ms
      On-Promote:
        - ""
      On-Demote:
    Wow: #ID
      Price: 20